function [idata, imeta_info] = load_eye_monitor_data(file_name, load_img)
%[idata, imeta_info] = load_eye_monitor_data(file_name, load_img)
% loads video file (custom file format) generated by eye monitor

if nargin < 1
    disp('usage: load_eye_monitor_data(file_name, load_img)');
    return;
end

meta_info_size=9;
little_endian=1;


%% try to open file, otherwise try sec filename, otherwise quit
[fi, message] = fopen(file_name, 'r', 'ieee-le');
if fi == -1
    file_name=strrep(file_name,'.eye','sec.eye');
    [fi, message] = fopen(file_name, 'r', 'ieee-le');
    warning('you don''t like cleaning up do you?! Stop that faff and get your thingies straight - loading sec.eye file for you');
    if fi==-1
        error(['There was a problem reading the following file:' char(13) file_name char(13) message]);
        return
    end
end

meta_info = fread(fi, meta_info_size, 'double');

size_x=meta_info(5);
size_y=meta_info(6);

% if loading very old data where meta_info 3 and 4 were not whisker
% position, these lines need to read:
%
% size_x=meta_info(5)-meta_info(3);
% size_y=meta_info(6)-meta_info(4);


if rem(size_y,1)>0 || rem(size_x,1)>0
    disp('NC Warning: File format is little endian -- this is probably an old file type');
    little_endian=0;
    fclose(fi);
    [fi, ~] = fopen(file_name, 'r', 'ieee-be');
    meta_info = fread(fi, meta_info_size, 'double');
    if meta_info(3)==0 || rem(meta_info(3),1)~=0
        size_x=meta_info(5);
        size_y=meta_info(6);
    else % for old data
        size_x=meta_info(5)-meta_info(3);
        size_y=meta_info(6)-meta_info(4);
    end
end

if size_x==0 || size_y==0
    disp('Warning: ifile probably corrupt - skipping');
    idata=[];
    imeta_info=[];
    return
end

%% get file size
fseek(fi, 0, 'eof');
file_size = ftell(fi);
fclose(fi);

%% open the file again - this time to read in the data
if little_endian
    [fi, ~] = fopen(file_name, 'r', 'ieee-le');
else
    [fi, ~] = fopen(file_name, 'r', 'ieee-be');
end

%% get all header information
% double = 8 bytes, uint8 = 1 byte
errors={};
nbr_frames=(file_size)/(size_x*size_y+meta_info_size*8);
if rem(nbr_frames,1)~=0
    disp('NC WARNING - nbr frames is not an integer - attemping to floor')
    nbr_frames=floor(nbr_frames);
end

if load_img
    idata=zeros(size_x,size_y,nbr_frames,'uint8');
else
    idata=[];
end
imeta_info=zeros(9,nbr_frames);

for ind=1:nbr_frames
    try
        imeta_info(:,ind) = fread(fi, meta_info_size, 'double');
        if load_img
            idata(:,:,ind) = uint8(reshape(fread(fi, size_x*size_y, 'uint8'),size_x,size_y));
        else
            fseek(fi,size_x*size_y,'cof');
        end
    catch err
        errors{end+1}=err.message;
    end
end
if ~isempty(errors)
    warning('eye_data loading error: %s\n',strjoin(regexprep(unique(errors),'[\n\r\t]',' ')));
end


%% read in the data

fclose(fi);
